[package]
name = "rust-to-c"
version = "0.1.0"
authors = [ "Alex Crichton <alex@alexcrichton.com>", 
            "Jonathan Price <jon.mark.price@gmail.com>"]
build = "build.rs"

[dependencies]
libc = "0.1"

[build-dependencies]
gcc = "0.3"
